Repository lyeskara/SOEN390, pull requests merged in 2023-03, with the labels that each got.

#143 Added functionalities to Groups Feature #25
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Network/CreateGroup.js
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/styles/GroupCreation.css
  frontend/src/styles/network.css
Labels: Functionality

#152 Fixed the styling of the other users profile
  frontend/src/App.js
  frontend/src/components/ProfileInfo/OtherUsersProfile.js
  frontend/src/styles/network.css
Labels: User Interface

#156 Minor Styling changes to Groups page
  frontend/src/components/Network/GroupNetwork.js
Labels: User Interface

#178 Minor Styling changes to Group Cards #2
  frontend/src/components/Network/GroupNetwork.js
Labels: User Interface

#192 Fixed the Group Image upload feature from Group Creation
  frontend/src/components/Jobs/CreateNewPosting.js
  frontend/src/components/Network/CreateEvent.js
  frontend/src/components/Network/CreateGroup.js
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/styles/GroupCreation.css
Labels: User Interface, Fix

#202 Job Posting Skills Create/Edit/Delete
  frontend/src/components/Jobs/CreateNewPosting.js
  frontend/src/components/Jobs/JobPostings.js
Labels: enhancement

#204 changed css
  frontend/src/components/ProfileInfo/EditProfile.js
  frontend/src/components/ProfileInfo/Profile.js
  frontend/src/styles/profile.css
Labels: bug

#211 Fixed the messaging styling
  frontend/src/components/DirectMessage/Messaging.css
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/components/Jobs/JobPostings.js
  frontend/src/components/Navbar.js
  frontend/src/images/paperclip.png
Labels: User Interface

#216 Add a pop up to confirm the connection was added
  frontend/src/components/connection/RequestsPage.js
  frontend/src/styles/network.css
Labels: enhancement, User Interface

#219 Modify general className
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/styles/Messaging.css
Labels: Fix

#218 #124 Implementation of the Joining/Leaving group feature
  frontend/src/App.js
  frontend/src/components/Network/CreateGroup.js
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/components/Network/GroupPage.js
Labels: enhancement, Functionality

#220 Add focus to chat list
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/styles/Messaging.css
Labels: User Interface

#228 Add the user picture in search bar, other user, and connection page
  frontend/src/components/ProfileInfo/OtherUsersProfile.js
  frontend/src/components/connection/ConnectionPage.js
  frontend/src/components/connection/RequestSent.js
  frontend/src/components/connection/RequestsPage.js
  frontend/src/components/connection/Search.js
  frontend/src/styles/network.css
Labels: User Interface, Fix

#229 41 sending documents
  frontend/src/components/DirectMessage/Messaging.js
Labels: user story

#247 fixed liking bug in user feed page
  frontend/src/components/UserFeedPage/Post.js
Labels: Fix

#248 Save job posts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/components/Jobs/SavedJobs.js
  frontend/src/styles/JobPostings.css
Labels: Functionality

#246 21 searching companies
  frontend/src/App.js
  frontend/src/components/connection/CompanySearch.js
  frontend/src/components/connection/Search.js
  frontend/src/styles/CompanySearch.css
Labels: user story

#250 Fixed job application bug
  frontend/src/components/Jobs/ApplyNow.js
Labels: Fix

#249 Post creation and feed display
  frontend/src/components/UserFeedPage/CreatPost.js
  frontend/src/components/UserFeedPage/Feed.js
  frontend/src/components/UserFeedPage/Post.js
  frontend/src/styles/createpost.css
  frontend/src/styles/feed.css
  frontend/src/styles/post.css
Labels: enhancement

#256 [bug fix] Fixing document required checkbox bug in create job posting
  frontend/src/components/Jobs/CreateNewPosting.js
Labels: Fix

#259 [#124 and #222] Group Page view members & Group Image responsiveness features
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/components/Network/GroupPage.js
Labels: enhancement, Functionality, Fix
