Repository lyeskara/SOEN390, pull requests merged in 2023-04, with the labels that each got.

#261 Added restrictions/requirements/confirmations to text inputs and user decisions.
  frontend/src/components/Jobs/CreateNewPosting.js
  frontend/src/components/Network/CreateGroup.js
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/components/Network/GroupPage.js
  frontend/src/components/ProfileInfo/EditProfile.js
  frontend/src/components/authentication/JoinNow.js
  frontend/src/components/authentication/SignIn.js
  frontend/src/components/connection/ConnectionPage.js
Labels: enhancement, User Interface

#267 Fix the job displayal for job seeker page
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/components/Jobs/SavedJobs.js
  frontend/src/styles/JobPostings.css
  frontend/src/styles/nav.css
Labels: User Interface

#270 [minor change] Removed sponsored posts from the Feed
  frontend/src/components/UserFeedPage/Feed.js
Labels: User Interface

#272 Fix search bug
  frontend/src/components/connection/Search.js
Labels: bug

#275 Adjusted logic to also include both recruiters and job seekers in the Active Members section
  frontend/src/components/Network/GroupPage.js
Labels: Fix

#279 Newsfeed fixes
  frontend/src/components/UserFeedPage/CreatPost.js
  frontend/src/components/UserFeedPage/Feed.js
Labels: Fix

#280 Added the Settings pages
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/components/Settings/ProfileInfoSetting.js
  frontend/src/components/Settings/Security.js
Labels: enhancement

#281 improve responsiveness of the pages
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/components/Jobs/ApplyNow.js
  frontend/src/components/Jobs/CreateNewPosting.js
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/components/Jobs/SavedJobs.js
  frontend/src/components/Network/CreateGroup.js
  frontend/src/components/Network/Event.js
  frontend/src/components/connection/RequestSent.js
  frontend/src/components/connection/RequestsPage.js
  frontend/src/styles/GroupCreation.css
  frontend/src/styles/JobPostings.css
  frontend/src/styles/Messaging.css
  frontend/src/styles/createpost.css
  frontend/src/styles/feed.css
  frontend/src/styles/network.css
Labels: Fix

#282 add change password feature
  frontend/src/App.js
  frontend/src/components/Navbar.js
  frontend/src/components/Settings/ChangePassword.js
  frontend/src/components/Settings/Security.js
  frontend/src/styles/nav.css
  frontend/src/styles/setting.css
Labels: Functionality

#286 Added styling to the notification page
  frontend/src/components/Notification.js
  frontend/src/styles/Notification.css
Labels: enhancement

#295 Fixed the styling and connection between pages
  frontend/src/components/Settings/Notificationsettings.js
  frontend/src/components/Settings/Security.js
Labels: Fix

#298 Navbar routing
  frontend/src/components/Navbar.js
Labels: high priority, Fix

#299 Date expiration job postings
  frontend/src/components/Jobs/Advertisements.js
  frontend/src/components/Jobs/CreateNewPosting.js
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/components/Jobs/JobPostings.js
Labels: Fix

#297 #38 Implementation of Group Admin + Site Admin functionalities
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/AdminFeed.js
  frontend/src/components/Admin/AdminUsers.js
  frontend/src/components/Network/GroupNetwork.js
  frontend/src/components/Network/GroupPage.js
  frontend/src/images/shield_icon.png
Labels: enhancement, Functionality

#313 Job seeker page responsive on mobile
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/styles/JobPostings.css
Labels: Fix

#316 Dm moderation
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/styles/DMModerationMenu.css
Labels: user story

#319 #23 Responsive Styling changes to DM moderation button.
  frontend/src/components/DirectMessage/Messaging.js
  frontend/src/images/icon_mark.png
Labels: enhancement, User Interface

#320 274 messaging error bug
  frontend/src/components/DirectMessage/Messaging.js
Labels: bug

#324 Add comments and docstring to files
  frontend/src/components/Admin/Admin.js
  frontend/src/components/Admin/AdminFeed.js
  frontend/src/components/Admin/AdminUsers.js
  frontend/src/components/Jobs/Advertisements.js
  frontend/src/components/Jobs/ApplyNow.js
  frontend/src/components/Jobs/CreateAdvertisement.js
  frontend/src/components/Jobs/JobPageForSeekers.js
  frontend/src/components/Jobs/JobPostings.js
  frontend/src/components/Linkedin.js
  frontend/src/components/Navbar.js
  frontend/src/components/Network/Event.js
  frontend/src/components/Notification.js
  frontend/src/components/ProfileInfo/OtherUsersProfile.js
  frontend/src/components/ProfileInfo/ProfileForm.js
  frontend/src/components/ProfileInfo/RecruiterFrom.js
  frontend/src/components/Settings/ProfileInfoSetting.js
  frontend/src/components/Settings/Security.js
  frontend/src/components/UserFeedPage/CreatPost.js
  frontend/src/components/UserFeedPage/Feed.js
  frontend/src/components/UserFeedPage/LoggedHomePage.js
  frontend/src/components/UserFeedPage/Post.js
  frontend/src/components/authentication/JoinNow.js
  frontend/src/components/connection/CompanySearch.js
  frontend/src/components/connection/RequestsPage.js
Labels: Fix

#327 Fix bug name setting
  frontend/src/components/Settings/ChangePassword.js
  frontend/src/components/Settings/NameSetting.js
Labels: Fix

#334 Add the contact field for recruiter
  frontend/src/components/Settings/NameSetting.js
Labels: enhancement

#336 Fixed styling of pages
  frontend/src/components/ProfileInfo/OtherRecruitersProfile.js
  frontend/src/components/ProfileInfo/OtherUsersProfile.js
  frontend/src/styles/network.css
Labels: Fix

#337 Add default picture to feed
  frontend/src/components/UserFeedPage/CreatPost.js
  frontend/src/components/UserFeedPage/Feed.js
Labels: Fix

#338 Comment out job notif
  frontend/src/components/Settings/Notificationsettings.js
Labels: Fix

#339 add default picture
  frontend/src/components/Notification.js
  frontend/src/components/UserFeedPage/Post.js
Labels: Fix
